version: "3.8"

services:
  fsb:
      build: .
      restart: unless-stopped
      container_name: fsb
      environment:
      # required
       - API_ID=2201304 # change this to your ID
       - API_HASH=4862ee2bf0fe8fbad582cb26d3d12e77 # change this to your HASH
       - BOT_TOKEN=6031469337:AAHdUKqkU3DLflSZ_32yWAVH6xiT0mOwbZk #TGFileDownloadBot
       - BIN_CHANNEL=-1001829780398 # paste channel ID
      ports:
       - 127.0.0.1:8000:80
      volumes:
       - $HOME/TG-FileStreamBot:/app/.env
